<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
class M_admin extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function lihatdata()
    {
        //return $this->db->get('tb_akun_admin');
        //return $this->db->query('SELECT username, password, tb_akun_admin.kode_role, nama_role FROM tb_akun_admin INNER JOIN tb_role_admin ON tb_akun_admin.kode_role = tb_role_admin.kode_role');
        $this->db->select('username, password, kode_role_admin, nama_role');
        $this->db->from('tb_akun_admin');
        $this->db->join('tb_role_admin', 'kode_role_admin = kode_role');
        return $this->db->get();
    }

    function lihatdatasatu($username)
    {
        $this->db->where("username",$username);
        return $this->db->get('tb_akun_admin');
    }

    function cekdata($username)
    {
        $this->db->where("username",$username);
        return $this->db->get('tb_akun_admin')->num_rows();
    }

    function tambahdata($array)
    {
        return $this->db->insert('tb_akun_admin',$array);
    }

    function editdata($username,$array)
    {
        $this->db->where("username",$username);
        return $this->db->update('tb_akun_admin',$array);
    }
    function hapus($username)
    {
        $this->db->where("username",$username);
        return $this->db->delete('tb_akun_admin');
    }
    function ambilroleadmin(){
        $this->db->order_by("nama_role","ASC");
        return $this->db->get('tb_role_admin');
    }
}
